### ISSUE TITLE
Install not working on yunohost 4.2.8.3

### ISSUE THREAD

**Issue by czen** [YunoHost-Apps/mygpo_ynh#16]
Tried installing mygpo_ynh on fresh virtual machine with yunohost 4.2.8.3 from command line

got error  about celery module

https://paste.yunohost.org/raw/amudujuhop

> ModuleNotFoundError: No module named 'celery.task'

Could reproduce by downloading VirtualBox image from https://yunohost.org/ru/install/hardware:virtualbox
then run system update from admin web ui, then try installing app from CLI

**Comment by obrenckle** [comment]
I'm answering to this issue because I just happened on this [post on the yunohost forum](https://forum.yunohost.org/t/mygpo-installation-error-erreur-a-linstallation-de-mygpo/23911) and I think both are linked.

While this error is about celery module and the one on the forum about a relation not existing, both happened during the `manage.py makemigrations` django step. I'm pretty it's not a command that should be run in production, and it isn't in [mygpo install documentation](https://gpoddernet.readthedocs.io/en/latest/dev/installation.html).
I think only the `manage.py migrate` should be run.
